Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from Login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls')),
]

Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id','profile_pic')

Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserForm, UserInfoForm
from Login_app.models import UserInfo
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def login_page(request):
    return render(request,'Login_app/login.html',context={})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
                #return render(request,'Login_app/index.html',context={})
            else:
                return HttpResponse("Account Is not Active")
        else:
            HttpResponse("Lgoin Details are Wrong")
    else:
        #return render(request,'Login_app/login.html',context={})
        return HttpResponseRedirect(reverse('Login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))



def index(request): 
    dict = {}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        dict = {'user_basic_info':user_basic_info, 'user_more_info':user_more_info}
    return render(request,'Login_app/index.html', context=dict)

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()

            registered = True

    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    dict = {'user_form':user_form, 'user_info_form':user_info_form,'registered':registered}
    return render(request,'Login_app/register.html', context=dict)

templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
   <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   </head>
   <body>

     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="navbar-nav">
    {% if user.is_authenticated %}       
 <a class="nav-item nav-link active" href="{% url 'Login_app:index' %}">Home </a>
 <a class="nav-item nav-link" href="{% url 'Login_app:logout' %}">Logout </a>

 {% else %}
<a class="nav-item nav-link" href="{% url 'Login_app:register' %}">Register </a>
<a class="nav-item nav-link" href="{% url 'Login_app:login' %}">Login </a>
{% endif %}

           </div>
     </nav>
     <div class="container" style="padding-top:20px">
  {% block body_block %}

  {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

   </body>
 </html>

templates/Login_app/index.html
{% extends "Login_app/base.html" %}
{% block body_block %}
{% if user.is_authenticated %}
<p> hi {{ user_basic_info.username }}</p>
<p> Your Email: {{ user_basic_info.email }}</p>
<p><a href="{{ user_more_info.facebook_id }}"> Facebook Profile </a></p>
<img src="/media/{{ user_more_info.profile_pic }}" width="200px" >
{% else %}
<div class="alert alert-primary">You are not logged in
</div>
{% endif %}

{% endblock %}

templates/Login_app/login.html
{% extends "Login_app/base.html" %}
{% block body_block %}
<h3>Please Login:</h3>
<form action="{% url 'Login_app:user_login' %}" method="POST">
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter Your Username" required class="form-control">
  <label for="password">Password</label>
  <input type="password" name="password" placeholder="Enter Your Password" required class="form-control">
  {% csrf_token %}
  <br>
  <input type="submit" name="submit" value="Login">
</form>


{% endblock %}

templates/Login_app/register.html
{% extends "Login_app/base.html" %}
{% load static %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">Congratlation Registration Successfully Done
</div>
{% else %}
<form method="POST" enctype="multipart/form-data">
    {{ user_form.as_p }}
    {{ user_info_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Register">

</form>
{% endif %}
{% endblock %}